name: Metrics
on:
  # schedule: [{cron: "0 12 * * *"}]
  workflow_dispatch:
  # push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: tiagoboeing
          template: classic
          base: header, activity, community, repositories, metadata
          commits_authoring: tiagoboeing,contato@tiagoboeing.com,tiagoboeing11@gmail.com
          config_timezone: America/Sao_Paulo
          plugin_wakatime: true
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_days: 365
