name: Website metrics
on:
  schedule: [{cron: "0 12 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics to markdown
        uses: lowlighter/metrics@latest
        with:
          template: markdown
          filename: metrics.markdown.md
          markdown: >-
            https://raw.githubusercontent.com/lowlighter/metrics/examples/metrics.markdown.template.md
          config_output: markdown
          token: ${{ secrets.METRICS_TOKEN }}

